services:
  db:
    container_name: db
    image: postgres:17.2
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    expose:
      - "5432"
    restart: always
  

  backend:
    container_name: backend
    build:    
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    # command: django-admin startproject core .
    command: python manage.py runserver
    environment:
      - DEBUG=1
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:





